algo=input('Digite algo:')
print(f"O tipo primitivo desse valor é {type(algo)}")
print(f"Só tem espaços? {algo.isspace()}")
print(f"É um número? {algo.isnumeric()}")
print(f"É alfábetico? {algo.isalpha()}")
print(f"É alfanúmerico? {algo.isalnum()}")
print(f"Está em maiúsculas?{algo.isupper()}")
print(f"Esta em minúsculas?{algo.islower()}")
print(f"Esta capitalizada?{algo.istitle()}")