a=input("Digite algo:")
print(f'O tipo primitivo desse valor é {type(a)}')
print(f"Só tem espaços? {a.isspace()}") 
print(f"È um número? {a.isnumeric()}")
print(f"È alfabético? {a.isalpha()}")
print(f"È alfanumérico? {a.isalnum()}")
print(f"Está em maiúsculas?{a.isupper()}")
print(f"Está em minúsculas?{a.islower()}")
print(f"Está capitalizada? {a.istitle()}")